package com.hanlin.pojo;

public class Dorm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_dorm.did
     *
     * @mbg.generated
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_dorm.sumpeople
     *
     * @mbg.generated
     */
    private Integer sumpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_dorm.stutas
     *
     * @mbg.generated
     */
    private String stutas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_dorm.did
     *
     * @return the value of b_dorm.did
     *
     * @mbg.generated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_dorm.did
     *
     * @param did the value for b_dorm.did
     *
     * @mbg.generated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_dorm.sumpeople
     *
     * @return the value of b_dorm.sumpeople
     *
     * @mbg.generated
     */
    public Integer getSumpeople() {
        return sumpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_dorm.sumpeople
     *
     * @param sumpeople the value for b_dorm.sumpeople
     *
     * @mbg.generated
     */
    public void setSumpeople(Integer sumpeople) {
        this.sumpeople = sumpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_dorm.stutas
     *
     * @return the value of b_dorm.stutas
     *
     * @mbg.generated
     */
    public String getStutas() {
        return stutas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_dorm.stutas
     *
     * @param stutas the value for b_dorm.stutas
     *
     * @mbg.generated
     */
    public void setStutas(String stutas) {
        this.stutas = stutas == null ? null : stutas.trim();
    }
}