package com.hanlin.pojo;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_record.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_record.did
     *
     * @mbg.generated
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_record.sumpeople
     *
     * @mbg.generated
     */
    private Integer sumpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_record.startdate
     *
     * @mbg.generated
     */
    private String startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_record.stopdate
     *
     * @mbg.generated
     */
    private String stopdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_record.id
     *
     * @return the value of b_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_record.id
     *
     * @param id the value for b_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_record.sid
     *
     * @return the value of b_record.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_record.sid
     *
     * @param sid the value for b_record.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_record.did
     *
     * @return the value of b_record.did
     *
     * @mbg.generated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_record.did
     *
     * @param did the value for b_record.did
     *
     * @mbg.generated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_record.sumpeople
     *
     * @return the value of b_record.sumpeople
     *
     * @mbg.generated
     */
    public Integer getSumpeople() {
        return sumpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_record.sumpeople
     *
     * @param sumpeople the value for b_record.sumpeople
     *
     * @mbg.generated
     */
    public void setSumpeople(Integer sumpeople) {
        this.sumpeople = sumpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_record.startdate
     *
     * @return the value of b_record.startdate
     *
     * @mbg.generated
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_record.startdate
     *
     * @param startdate the value for b_record.startdate
     *
     * @mbg.generated
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_record.stopdate
     *
     * @return the value of b_record.stopdate
     *
     * @mbg.generated
     */
    public String getStopdate() {
        return stopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_record.stopdate
     *
     * @param stopdate the value for b_record.stopdate
     *
     * @mbg.generated
     */
    public void setStopdate(String stopdate) {
        this.stopdate = stopdate;
    }
}