package com.hanlin.pojo;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_student.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_student.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_student.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_student.college
     *
     * @mbg.generated
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_student.sdate
     *
     * @mbg.generated
     */
    private String sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_student.did
     *
     * @mbg.generated
     */
    private Integer did;
    private int sumpeople;

    public int getSumpeople() {
		return sumpeople;
	}

	public void setSumpeople(int sumpeople) {
		this.sumpeople = sumpeople;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_student.sid
     *
     * @return the value of b_student.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_student.sid
     *
     * @param sid the value for b_student.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_student.sname
     *
     * @return the value of b_student.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_student.sname
     *
     * @param sname the value for b_student.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_student.sex
     *
     * @return the value of b_student.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_student.sex
     *
     * @param sex the value for b_student.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_student.college
     *
     * @return the value of b_student.college
     *
     * @mbg.generated
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_student.college
     *
     * @param college the value for b_student.college
     *
     * @mbg.generated
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_student.sdate
     *
     * @return the value of b_student.sdate
     *
     * @mbg.generated
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_student.sdate
     *
     * @param sdate the value for b_student.sdate
     *
     * @mbg.generated
     */
    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_student.did
     *
     * @return the value of b_student.did
     *
     * @mbg.generated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_student.did
     *
     * @param did the value for b_student.did
     *
     * @mbg.generated
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}