package com.hanlin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.hanlin.pojo.Dorm;

public interface DormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dorm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dorm
     *
     * @mbg.generated
     */
    int insert(Dorm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dorm
     *
     * @mbg.generated
     */
    int insertSelective(Dorm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dorm
     *
     * @mbg.generated
     */
    Dorm selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dorm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dorm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dorm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dorm record);

    @Select("select * from b_dorm where stutas=#{sex} and sumpeople<8")
	List<Dorm> getDormList(@Param("sex")String sex);

    @Update("update b_dorm set sumpeople=sumpeople+1 where did=#{did}")
    void upDormSumpeople(@Param("did")int did);

    @Update("update b_dorm set sumpeople=sumpeople-1 where did=#{did}")
	void upDormSumPeo(@Param("did")int did);
}