package com.hanlin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.hanlin.pojo.Record;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_record
     *
     * @mbg.generated
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_record
     *
     * @mbg.generated
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_record
     *
     * @mbg.generated
     */
    Record selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Record record);

    @Update("update b_record set stopdate=#{format} where stopdate is  NUll and sid=#{sid}")
	int updateRecord(@Param("sid")int sid, @Param("format")String format);
    
    @Select("select * from b_record where sid=#{sid}")
	List<Record> getRecordList(@Param("sid")int sid);
}